apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.service: heater-sensor
  name: heater-sensor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: heater-sensor
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.network/household-network: "true"
        io.service: heater-sensor
    spec:
      containers:
      - image: ubervelocity/sca_heater:1.0
        imagePullPolicy: ""
        name: heater-sensor
        resources: {}
        env:
        - name: KAFKA
          value: '''kafka-29091'':''kafka2-29092'':''kafka3-29093'''
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
