apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.service: heater-sensor
  name: heater-sensor
spec:
  ports:
  - name: "3010"
    port: 3010
    targetPort: 3010
  selector:
    io.kompose.service: heater-sensor
status:
  loadBalancer: {}
