apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    io.service: vacuum-sensor
  name: vacuum-sensor
spec:
  ports:
  - name: "3013"
    port: 3013
    targetPort: 3013
  selector:
    io.kompose.service: vacuum-sensor
status:
  loadBalancer: {}
