apiVersion: v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  containers:
  - name: zookeeper
    image: bitnami/zookeeper:3
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
    ports:
      - containerPort: 2181