version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
     - '2181:2181'
    volumes:
     - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka2_data:/bitnami'
    depends_on:
      - zookeeper
    #command: docker exec docker_kafka_cluster_kafka_1 kafka-topics.sh --create --zookeeper zookeeper --replication-factor 3 --partitions 3 --topic historical
  kafka2:
    image: 'bitnami/kafka:2'
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:2'
    ports:
      - '9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka3_data:/bitnami'
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local